part of 'h2_app_bar.dart';

class _CustomAppBar extends H2AppBar {
  const _CustomAppBar({
    Key? key,
    Widget? leading,
    bool automaticallyImplyLeading = true,
    Widget? title,
    List<Widget>? actions,
    Widget? flexibleSpace,
    PreferredSizeWidget? bottom,
    double? elevation,
    double? scrolledUnderElevation,
    Color? shadowColor,
    Color? surfaceTintColor,
    ShapeBorder? shape,
    Color? backgroundColor,
    Color? foregroundColor,
    IconThemeData? iconTheme,
    TextTheme? textTheme,
    bool primary = true,
    bool? centerTitle,
    bool excludeHeaderSemantics = false,
    double? titleSpacing,
    double toolbarOpacity = 1.0,
    double bottomOpacity = 1.0,
    double? toolbarHeight,
    double? leadingWidth,
    TextStyle? toolbarTextStyle,
    TextStyle? titleTextStyle,
    SystemUiOverlayStyle? systemOverlayStyle,
    IconThemeData? actionsIconTheme,
  }) : super._(
          automaticallyImplyLeading: automaticallyImplyLeading,
          title: title,
          key: key,
          backgroundColor: backgroundColor,
          centerTitle: centerTitle,
          titleSpacing: titleSpacing,
          shadowColor: shadowColor,
          actions: actions,
          systemOverlayStyle: systemOverlayStyle,
          titleTextStyle: titleTextStyle,
          scrolledUnderElevation: scrolledUnderElevation,
          actionsIconTheme: actionsIconTheme,
          bottom: bottom,
          elevation: elevation,
          bottomOpacity: bottomOpacity,
          toolbarOpacity: toolbarOpacity,
          shape: shape,
          toolbarHeight: toolbarHeight,
          surfaceTintColor: surfaceTintColor,
          primary: primary,
          toolbarTextStyle: toolbarTextStyle,
          excludeHeaderSemantics: excludeHeaderSemantics,
          flexibleSpace: flexibleSpace,
          foregroundColor: foregroundColor,
          iconTheme: iconTheme,
          leading: leading,
          leadingWidth: leadingWidth,
        );

  @override
  Widget build(BuildContext context) {
    return AppBar(
      toolbarTextStyle: toolbarTextStyle,
      primary: primary,
      surfaceTintColor: surfaceTintColor,
      shape: shape,
      toolbarHeight: toolbarHeight ?? kToolbarHeight,
      backgroundColor: backgroundColor,
      bottom: bottom,
      actions: actions,
      actionsIconTheme: actionsIconTheme,
      automaticallyImplyLeading: automaticallyImplyLeading,
      centerTitle: centerTitle,
      elevation: elevation,
      excludeHeaderSemantics: excludeHeaderSemantics,
      flexibleSpace: flexibleSpace,
      foregroundColor: foregroundColor,
      iconTheme: iconTheme,
      leading: leading,
      leadingWidth: leadingWidth,
      scrolledUnderElevation: scrolledUnderElevation,
      shadowColor: shadowColor,
      systemOverlayStyle: systemOverlayStyle,
      title: title,
      titleSpacing: titleSpacing,
      titleTextStyle: titleTextStyle,
      bottomOpacity: bottomOpacity,
      toolbarOpacity: toolbarOpacity,
    );
  }
}
